name: shawnj's blog
url: http://b.shawnj.co
# description: A stylish blog using the Solarized color palette

name: shawnj's blog
markdown: redcarpet
pygments: true
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']